// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MyBillingApp.Entities;
using System;

namespace MyBillingApp.Migrations
{
    [DbContext(typeof(ClientContext))]
    [Migration("20180116135357_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyBillingApp.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("BillableHours");

                    b.Property<int>("BillingDay");

                    b.Property<int>("HourlyRate");

                    b.Property<bool>("IsPaid");

                    b.Property<string>("Name");

                    b.Property<double>("PayableAmount");

                    b.HasKey("Id");

                    b.ToTable("ClientList");
                });
#pragma warning restore 612, 618
        }
    }
}
